### ISSUE TITLE
GPU Memory Consumption for IG Inference

### ISSUE THREAD

**Issue by YoumiMa** [Hytn/DocRED-HWE#1]
Hi, thanks for the excellent work! I'm wondering if you could help me confirm the memory budget for IG inference.

I was trying to run Step 2 of the preparation on two NVIDIA RTX A6000 48GB GPUs with:

`CUDA_VISIBLE_DEVICES=1,2 python IG_inference.py --infer_method ig_infer --load_path /path/to/trained/atlop/ckpt/best.ckpt --model_name_or_path bert-base-cased --transformer_type bert`

and got the OOM error message below.

```
Traceback (most recent call last):
  File "IG_inference.py", line 321, in <module>
    main()
  File "IG_inference.py", line 317, in main
    infer_methods[args.infer_method](model, infer_features, args)
  File "IG_inference.py", line 79, in ig_infer
    gradient = grad(outputs=label_logit, inputs=inp_embs, retain_graph=True)[0].squeeze(0)
  File "/home/ma.y/.conda/envs/docre-py3.8/lib/python3.8/site-packages/torch/autograd/__init__.py", line 275, in grad
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: CUDA out of memory. Tried to allocate 72.00 MiB (GPU 0; 47.54 GiB total capacity; 45.29 GiB already allocated; 38.69 MiB free; 45.69 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

Could you please provide some information about the GPU memory requirement to run the IG inference? BTW, the code ends properly if I change `--infer_method` from `ig_infer` to `grad_infer`.

Also, it seems to me that the data parallel didn't work correctly, as the memory was only allocated on the first GPU I specified.

Thank you in advance for your time and patience !

========

Some modifications I made in order to make the code run:
+ commented out L.17 in model.py
+ changed L.274 from `model_name_or_path = BERT_PATH_DIR + args.model_name_or_path` to ` model_name_or_path = args.model_name_or_path`
+ added the following lines after L.307 in IG_inference.py:

```   
if isinstance(model, torch.nn.DataParallel):
        model = model.module
```

Some (maybe important) package versions:

```
# Name                    Version                   Build  Channel               
apex                      0.1                      pypi_0    pypi
python                    3.8.13               h12debd9_0  
pytorch                   1.11.0          py3.8_cuda11.3_cudnn8.2.0_0    pytorch
transformers              4.14.1             pyhd3eb1b0_0 
```

**Comment by 12Jack21** [comment]
Yep, `ig_infer` will consume more GPU memory than `grad_infer`, and cost more time to finish the task.
Since we have not done some extra paralell optimization yet, only one GPU (memory > 24GB) can be used.
We do some modification to the code, and it works now, you can use the latest commit c5bf77e.
Feel free to reopen this issue if you have other derivational problems.

**Comment by 12Jack21** [comment]
Fixed with commit c5bf77ee1c69bca804df861644b8181822723bdd

**Comment by YoumiMa** [comment]
Thanks for the quick fix!
I'm contacting you again about an issue I encountered when executing step 3.
Specifically, when I ran `python getds.py --model_type bert-base-cased`, I got the error message below:

```
Traceback (most recent call last):
  File "getds.py", line 2, in <module>
    from run_utils import build_entity_attack_dataset, enp_topk, get_atlop_model
  File "/home/ma.y/Research/DocRED-HWE/run_utils.py", line 123
    def enp_topk(args, model, model_type, tokenizer, dataset/ig_pkl_path, file_in="dataset/docred/dev_keys_new.json", limit=False):
                                                            ^
SyntaxError: invalid syntax
```

Could you please help me resolve the issue again?

Thanks a lot!

**Comment by 12Jack21** [comment]
That is caused by typos in function parameters, fix in commit 03d7ed9

**Comment by YoumiMa** [comment]
Thank you for the fix, and sorry for repeatedly bothering you.

After pulling the latest commit, I reran `python getds.py --model_type bert-base-cased` and get error messages as below:

```
Traceback (most recent call last):
  File "getds.py", line 16, in <module>
    enp_topk(args, model, model_type, tokenizer, "dataset/ig_pkl")
  File "/home/ma.y/Research/DocRED-HWE/run_utils.py", line 154, in enp_topk
    with open(ig_pkl_path, "rb") as dig:
IsADirectoryError: [Errno 21] Is a directory: 'dataset/ig_pkl'
```

where `dataset/ig_pkl` is indeed a directory containing IG results.

Would you still be kind enough to help me resolve the error?
